"""add_project_tables

Revision ID: 0aa98a797c64
Revises: 4efaa82adf21
Create Date: 2025-05-31 09:34:29.024808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa98a797c64'
down_revision = '4efaa82adf21'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###