"""fix_agent_relation

Revision ID: 0fc6f018ab41
Revises: a394dcf9346f
Create Date: 2025-06-05 14:19:32.660201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc6f018ab41'
down_revision = 'a394dcf9346f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###