"""add_main_category

Revision ID: 135732ab30d5
Revises: 
Create Date: 2025-05-29 18:30:06.341665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135732ab30d5'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###