"""add_agents_table

Revision ID: 14f1b26bc1d5
Revises: 44c4a13886af
Create Date: 2025-06-01 10:19:22.674061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f1b26bc1d5'
down_revision = '44c4a13886af'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###