"""add agent oauth_account_id

Revision ID: 2c2e3e47ad2c
Revises: 428c62c1010a
Create Date: 2025-07-03 17:38:34.293096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2e3e47ad2c'
down_revision = '428c62c1010a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('oauth_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agents', 'oauth_accounts', ['oauth_account_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'oauth_account_id')
    # ### end Alembic commands ###