"""add project fixes

Revision ID: 2df634e62a73
Revises: 0aa98a797c64
Create Date: 2025-05-31 10:01:48.684194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df634e62a73'
down_revision = '0aa98a797c64'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###