"""added_relevance_score

Revision ID: 3edf6dacf69f
Revises: 9e4317b80075
Create Date: 2025-07-06 18:19:21.666483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edf6dacf69f'
down_revision = '9e4317b80075'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_agent_execution_mapper', sa.Column('keyword_relevance', sa.Float(), nullable=True))
    op.add_column('reddit_agent_execution_mapper', sa.Column('semantic_relevance', sa.Float(), nullable=True))
    op.add_column('reddit_agent_execution_mapper', sa.Column('combined_relevance', sa.Float(), nullable=True))
    op.add_column('reddit_agent_execution_mapper', sa.Column('llm_relevance', sa.Float(), nullable=True))
    op.add_column('reddit_agent_execution_mapper', sa.Column('matched_query', sa.String(), nullable=True))
    op.add_column('reddit_agent_execution_mapper', sa.Column('sort_method', sa.String(), nullable=True))
    op.add_column('reddit_posts', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('reddit_posts', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_posts', 'text')
    op.drop_column('reddit_posts', 'comment_count')
    op.drop_column('reddit_agent_execution_mapper', 'sort_method')
    op.drop_column('reddit_agent_execution_mapper', 'matched_query')
    op.drop_column('reddit_agent_execution_mapper', 'llm_relevance')
    op.drop_column('reddit_agent_execution_mapper', 'combined_relevance')
    op.drop_column('reddit_agent_execution_mapper', 'semantic_relevance')
    op.drop_column('reddit_agent_execution_mapper', 'keyword_relevance')
    # ### end Alembic commands ###