"""fix_agent_relationss

Revision ID: 40429546cd97
Revises: b75eb8e25aff
Create Date: 2025-06-05 14:29:11.244609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40429546cd97'
down_revision = 'b75eb8e25aff'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###