"""update refresh and access token fix

Revision ID: 428c62c1010a
Revises: 81d0b78c568a
Create Date: 2025-06-30 18:06:05.893492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428c62c1010a'
down_revision = '81d0b78c568a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_accounts', 'access_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('oauth_accounts', 'refresh_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_accounts', 'refresh_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('oauth_accounts', 'access_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###