"""add project fixe

Revision ID: 44c4a13886af
Revises: 2df634e62a73
Create Date: 2025-05-31 10:03:16.389947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c4a13886af'
down_revision = '2df634e62a73'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###