"""add_user_table_

Revision ID: 4efaa82adf21
Revises: 5339117f4b48
Create Date: 2025-05-29 19:03:49.318039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4efaa82adf21'
down_revision = '5339117f4b48'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###