"""add_user_table

Revision ID: 5339117f4b48
Revises: a6644b40ce1c
Create Date: 2025-05-29 18:51:58.096319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5339117f4b48'
down_revision = 'a6644b40ce1c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###