"""fix_agent_relatio

Revision ID: 6f7e642d87de
Revises: 0fc6f018ab41
Create Date: 2025-06-05 14:27:28.255726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7e642d87de'
down_revision = '0fc6f018ab41'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###