"""update refresh and access token

Revision ID: 81d0b78c568a
Revises: c40652d71be7
Create Date: 2025-06-30 18:02:39.369200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d0b78c568a'
down_revision = 'c40652d71be7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###