"""fix renaming

Revision ID: 9e1338ab1cf8
Revises: fb76e35e2ee7
Create Date: 2025-06-28 12:33:52.777848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1338ab1cf8'
down_revision = 'fb76e35e2ee7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###