"""changed_keywords

Revision ID: 9e4317b80075
Revises: 2c2e3e47ad2c
Create Date: 2025-07-04 20:59:26.979680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e4317b80075'
down_revision = '2c2e3e47ad2c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('agent_keywords', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('agents', 'keywords')
    op.drop_index('ix_oauth_accounts_id', table_name='oauth_accounts')
    op.drop_index('ix_oauth_accounts_user_id', table_name='oauth_accounts')
    op.drop_constraint('unique_provider_user', 'oauth_accounts', type_='unique')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_provider_user', 'oauth_accounts', ['provider', 'provider_user_id'])
    op.create_index('ix_oauth_accounts_user_id', 'oauth_accounts', ['user_id'], unique=False)
    op.create_index('ix_oauth_accounts_id', 'oauth_accounts', ['id'], unique=False)
    op.add_column('agents', sa.Column('keywords', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('agents', 'agent_keywords')
    # ### end Alembic commands ###