"""add_agent_relation

Revision ID: a394dcf9346f
Revises: cadd83b062ac
Create Date: 2025-06-05 14:10:05.576412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a394dcf9346f'
down_revision = 'cadd83b062ac'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###