"""update_agent_schema

Revision ID: b6fda4f70d74
Revises: 14f1b26bc1d5
Create Date: 2025-06-01 14:05:16.166026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6fda4f70d74'
down_revision = '14f1b26bc1d5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('agent_status', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('expectations', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('mode', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('review_period', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('review_minutes', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('advanced_settings', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('platform_settings', sa.JSON(), nullable=True))
    op.alter_column('agents', 'goals',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('agents', 'min_upvotes')
    op.drop_column('agents', 'relevance_threshold')
    op.drop_column('agents', 'company_keywords')
    op.drop_column('agents', 'industry_filter')
    op.drop_column('agents', 'target_accounts')
    op.drop_column('agents', 'description')
    op.drop_column('agents', 'status')
    op.drop_column('agents', 'restrict_to_goal_subreddits')
    op.drop_column('agents', 'target_audience')
    op.drop_column('agents', 'target_companies')
    op.drop_column('agents', 'max_age_days')
    op.drop_column('agents', 'sentiment_filter')
    op.drop_column('agents', 'excluded_keywords')
    op.drop_column('agents', 'expectation')
    op.drop_column('agents', 'target_subreddits')
    op.drop_column('agents', 'check_comments')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('check_comments', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('target_subreddits', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('expectation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('excluded_keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('sentiment_filter', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('max_age_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('target_companies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('target_audience', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('restrict_to_goal_subreddits', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('target_accounts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('industry_filter', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('company_keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('relevance_threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('min_upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('agents', 'goals',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('agents', 'platform_settings')
    op.drop_column('agents', 'advanced_settings')
    op.drop_column('agents', 'review_minutes')
    op.drop_column('agents', 'review_period')
    op.drop_column('agents', 'mode')
    op.drop_column('agents', 'expectations')
    op.drop_column('agents', 'agent_status')
    # ### end Alembic commands ###