"""fix_agent_relations

Revision ID: b75eb8e25aff
Revises: 6f7e642d87de
Create Date: 2025-06-05 14:28:18.674002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75eb8e25aff'
down_revision = '6f7e642d87de'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###