"""update twitter relation

Revision ID: b8def814a720
Revises: 2a677c4e4b8a
Create Date: 2025-06-08 15:25:10.213645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8def814a720'
down_revision = '2a677c4e4b8a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_posts', sa.Column('hashtags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_posts', 'hashtags')
    # ### end Alembic commands ###