"""add oauth_state table

Revision ID: c40652d71be7
Revises: 57e8e5beb5ee
Create Date: 2025-06-30 16:46:37.719312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40652d71be7'
down_revision = '57e8e5beb5ee'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###