"""add_agent_resuts

Revision ID: cadd83b062ac
Revises: d7e8d4c74c95
Create Date: 2025-06-04 17:22:52.415708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadd83b062ac'
down_revision = 'd7e8d4c74c95'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('last_run', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'last_run')
    # ### end Alembic commands ###