"""add_project_uuid

Revision ID: d7e8d4c74c95
Revises: b6fda4f70d74
Create Date: 2025-06-01 14:39:31.534875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e8d4c74c95'
down_revision = 'b6fda4f70d74'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('uuid', sa.String(), nullable=True))
    op.create_index(op.f('ix_projects_uuid'), 'projects', ['uuid'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_uuid'), table_name='projects')
    op.drop_column('projects', 'uuid')
    # ### end Alembic commands ###