"""remve_new_category

Revision ID: f87b9bc54c61
Revises: 135732ab30d5
Create Date: 2025-05-29 18:46:13.902842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87b9bc54c61'
down_revision = '135732ab30d5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###