"""update user model

Revision ID: fb76e35e2ee7
Revises: b95e05783600
Create Date: 2025-06-28 09:19:59.174620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb76e35e2ee7'
down_revision = 'b95e05783600'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('access_key', sa.String(length=250), nullable=True))
    op.add_column('user_tokens', sa.Column('refresh_key', sa.String(length=250), nullable=True))
    op.add_column('user_tokens', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_tokens', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_user_tokens_access_key'), 'user_tokens', ['access_key'], unique=False)
    op.create_index(op.f('ix_user_tokens_refresh_key'), 'user_tokens', ['refresh_key'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_user_tokens_refresh_key'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_access_key'), table_name='user_tokens')
    op.drop_column('user_tokens', 'expires_at')
    op.drop_column('user_tokens', 'created_at')
    op.drop_column('user_tokens', 'refresh_key')
    op.drop_column('user_tokens', 'access_key')
    # ### end Alembic commands ###