version: "3.8"
services:
  ragent:
    build:
      context: ./ragent
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ragent:/app
      - twitter_cookies:/app/cookies
      - sentence_transformer_cache:/app/model_cache
    environment:
      - POSTGRES_DSN=${POSTGRES_DSN}
      - SYNC_POSTGRES_DSN=${SYNC_POSTGRES_DSN}
      - REDIS_URL=${REDIS_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - TWITTER_EMAIL=${TWITTER_EMAIL}
      - TWITTER_PASSWORD=${TWITTER_PASSWORD}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - EXA_API_KEY=${EXA_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    networks:
      - market-network
    restart: unless-stopped
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/app"

  celery_worker:
    build:
      context: ./ragent
      dockerfile: Dockerfile
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - POSTGRES_DSN=${POSTGRES_DSN}
      - SYNC_POSTGRES_DSN=${SYNC_POSTGRES_DSN}
      - REDIS_URL=${REDIS_URL}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - TWITTER_EMAIL=${TWITTER_EMAIL}
      - TWITTER_PASSWORD=${TWITTER_PASSWORD}
      - EXA_API_KEY=${EXA_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    networks:
      - market-network
    restart: unless-stopped
    volumes:
      - ./ragent:/app
      - twitter_cookies:/app/cookies
      - sentence_transformer_cache:/app/model_cache
    command: celery -A app.celery_app worker -Q default --loglevel=info

  celery_beat:
    build:
      context: ./ragent
      dockerfile: Dockerfile
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - POSTGRES_DSN=${POSTGRES_DSN}
      - SYNC_POSTGRES_DSN=${SYNC_POSTGRES_DSN}
      - REDIS_URL=${REDIS_URL}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - TWITTER_EMAIL=${TWITTER_EMAIL}
      - TWITTER_PASSWORD=${TWITTER_PASSWORD}
      - EXA_API_KEY=${EXA_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    networks:
      - market-network
    restart: unless-stopped
    volumes:
      - ./ragent:/app
      - twitter_cookies:/app/cookies
      - sentence_transformer_cache:/app/model_cache
    command: celery -A app.celery_app beat --loglevel=info

  flower:
    build:
      context: ./ragent
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - POSTGRES_DSN=${POSTGRES_DSN}
      - SYNC_POSTGRES_DSN=${SYNC_POSTGRES_DSN}
      - REDIS_URL=${REDIS_URL}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - TWITTER_EMAIL=${TWITTER_EMAIL}
      - TWITTER_PASSWORD=${TWITTER_PASSWORD}
      - EXA_API_KEY=${EXA_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    depends_on:
      - redis
      - celery_worker
      - qdrant
    networks:
      - market-network
    restart: unless-stopped
    volumes:
      - ./ragent:/app
      - twitter_cookies:/app/cookies
      - sentence_transformer_cache:/app/model_cache
    command: celery -A app.celery_app flower --port=5555

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - market-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "5050:80" # Expose pgAdmin on port 5050
    environment:
      PGADMIN_DEFAULT_EMAIL: aniket@agentic.ai
      PGADMIN_DEFAULT_PASSWORD: aniket@agentic.ai
      PGADMIN_DISABLE_POSTFIX: false
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    volumes:
      - ./server.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - market-network
    restart: unless-stopped

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - market-network
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    networks:
      - market-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "timeout", "1", "bash", "-c", ">/dev/tcp/localhost/6333"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  scheduler_worker:
    build:
      context: ./ragent
      dockerfile: Dockerfile
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - POSTGRES_DSN=${POSTGRES_DSN}
      - SYNC_POSTGRES_DSN=${SYNC_POSTGRES_DSN}
      - REDIS_URL=${REDIS_URL}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - TWITTER_EMAIL=${TWITTER_EMAIL}
      - TWITTER_PASSWORD=${TWITTER_PASSWORD}
      - EXA_API_KEY=${EXA_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    networks:
      - market-network
    restart: unless-stopped
    volumes:
      - ./ragent:/app
      - twitter_cookies:/app/cookies
      - sentence_transformer_cache:/app/model_cache
    command: celery -A app.celery_app worker -Q scheduler -c 1 --loglevel=info

  smtp-service:
    image: axllent/mailpit
    restart: unless-stopped
    container_name: smtp
    networks:
      - market-network
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres-data:
  twitter_cookies:
  qdrant-data:
  sentence_transformer_cache:
    name: market_agent_sentence_transformer_cache

networks:
  market-network:
    driver: bridge
